### ISSUE TITLE
Cannot extract files with a tab character

### ISSUE THREAD

**Issue by FichteFoll** [packagecontrol/package_reviewer#1]
```
Traceback (most recent call last):
  File "E:\Development\Sublime\package_reviewer\package_reviewer\repo_tools.py", line 70, in download
    zipf.extractall(path=str(dirpath))
  File "c:\python35\Lib\zipfile.py", line 1344, in extractall
    self.extract(zipinfo, path, pwd)
  File "c:\python35\Lib\zipfile.py", line 1332, in extract
    return self._extract_member(member, path, pwd)
  File "c:\python35\Lib\zipfile.py", line 1395, in _extract_member
    open(targetpath, "wb") as target:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Fichte\\AppData\\Local\\Temp\\pkg-rev_w6sei_6a\lyzz0612-Cocos-Creator-Snippet-16f53bc\\creator_snippet\\cc\\Boolean\t.sublime-snippet'
```

**Comment by FichteFoll** [comment]
Note to self: Tab characters are not valid in filenames on Windows. Ideally I would post an error message when I encounter invalid characters in filenames inside the zip archive, which is mostly relevant for Windows systems. For simplification, I will most likely require these regardless of whether the package should be installable on Windows or not. Just use sane file names.
