### ISSUE TITLE
ImportError: No module named pathlib

### ISSUE THREAD

**Issue by evandrocoan** [packagecontrol/package_reviewer#9]
I tried to install it but seems I do not have this module `pathlib`. Should this package installer install it, when I do not have it?

```
$ pip install st-package-reviewer
Collecting st-package-reviewer
  Downloading st_package_reviewer-0.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\profes~1\appdata\local\temp\pip-build-exvhzl\st-package-reviewer\setup.py", line 2, in <module>
        from pathlib import Path
    ImportError: No module named pathlib

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\profes~1\appdata\local\temp\pip-build-exvhzl\st-package-reviewer\
```

I am on Windows 10 with anaconda `conda --version` -> `conda 4.3.18`.

Later by following:

1. https://github.com/nvbn/thefuck/issues/287 OSX: "ImportError: No module named pathlib" 

I installed successfully this package. However after trying to run it I got this error:
```
$ st_package_reviewer
Traceback (most recent call last):
  File "f:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "f:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "F:\Python27\Scripts\st_package_reviewer.exe\__main__.py", line 5, in <module>
  File "f:\python27\lib\site-packages\st_package_reviewer\__main__.py", line 106
    print("### Repository checks ###", file=out)
                                           ^
SyntaxError: invalid syntax
```

**Comment by evandrocoan** [comment]
I just noticed this required python 3.4 while I am on python 2.7.13
```
$ python --version
Python 2.7.13 :: Anaconda custom (32-bit)
```
